# Site settings
title: focus lost
author: Cory Evan Wright
author_url: http://coryevan.com
email: BeSublime@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Conversion
markdown: kramdown
highlighter: rouge

# Serving
host:    0.0.0.0

exclude: ['node_modules', 'Guardfile', 'Gemfile', 'Gemfile.lock', 'package.json']
